[aws]
disabled = true

[gcloud]
disabled = true

[rust]
disabled = true

[python]
disabled = true

[package]
disabled = true

[hostname]
disabled = true

[username]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

