#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrdb ~/.cache/wal/colors.Xresources
$HOME/dotfiles/polybar/launch.sh
xsetroot -cursor_name left_ptr

bspc wm -O DPI-3 HDMI-1

bspc monitor DP-3 -d I II III
bspc monitor HDMI-1 -d IV V VI

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a fzfapp monitor=focused state=floating center=true rectangle=400x300+0+0
bspc rule -a fzfwindow monitor=focused state=floating center=true rectangle=400x300+0+0
bspc rule -a fzfwallpaper monitor=focused state=floating center=true rectangle=1200x800+0+0
