#!/bin/bash

export FZF_DEFAULT_OPTS="--reverse --prompt ' ' --color=prompt:#19cb00,marker:#19cb00,pointer:#19cb00 --pointer ''"
# get classname of window
function widtowname() {
	wid=$1
	res=$(bspc query -T -n $wid | jq '.client.className' | sed 's/^"\(.*\)"$/\1/')
	echo "${res,,}"
}

export -f widtowname

function getwids() {
	res=$(bspc query -N -n '.window')
	echo "$res"
}

# Change the formatting of the option here
function getoptions() {
	while IFS= read -r line; do
		echo "[$(widtowname $line)] $(xtitle $line)";
	done <<< $1
}

wids=$(getwids)
choice=$(getoptions "$wids" | cat -n | fzf --with-nth 2.. | awk '{{print $1}}')
idx=$((choice - 1))
echo "choice: $choice, idx: $idx"
mapfile -t wids_arr <<< "$wids"
wid="${wids_arr[idx]}"

# Need to focus window by id
# desktop=$(bspc query -D -n "$wid")
# is_tiled=$(bspc query -T -d $desktop | jq -er '.layout == "tiled"')

# echo "desktop: $desktop"
# echo "is_tiled: $is_tiled"
bspc node -f $wid && exit 0
