#!/usr/bin/bash

# monitor=$(echo -e '0\n1' | fzf --prompt 'monitor ')
#
# if [ -z "$monitor" ]; then
# 	exit 0;
# fi

image=$(find \
	~/dotfiles/wallpapers \
	/usr/share/backgrounds/archlinux \
	-type f \( \
		-iname "*.jpg" \
		-o -iname "*.jpeg" \
		-o -iname "*.png" \
		-o -iname "*.gif" \
		-o -iname "*.bmp" \
		-o -iname "*.tiff" \
		-o -iname "*.webp" \) \
	| fzf --preview='kitty icat --clear --transfer-mode=memory --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 {}')

if [ -z "$image" ]; then
	exit 0;
fi

nitrogen --head=0 --set-auto $image --save
nitrogen --head=1 --set-auto $image --save
wal -i $image -n -s --cols16 darken

# reload qtile
qtile cmd-obj -o cmd -f reload_config
