#!/usr/bin/bash

image=$(find \
	~/dotfiles/wallpapers \
	/usr/share/backgrounds/archlinux \
	-type f \( \
		-iname "*.jpg" \
		-o -iname "*.jpeg" \
		-o -iname "*.png" \) \
	| fzf --preview='kitty icat --clear --transfer-mode=memory --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 {}')

if [ -z "$image" ]; then
	exit 0;
fi

matugen image "$image"
sleep 1 # Doesn't work if I remove this for some reason
